/**
 * sampleCrates.js
 * Base de datos curada de vinilos y gemas clásicas de sampleo para VX-CHOP.
 * Categorizadas para beatmakers y crate diggers: Soul Jazz, Rare Soul, Jazz Rock Progresivo,
 * Música Ambiental / Library Music, Japanese Fusion y Drum Breaks.
 */

export const CRATE_GENRES = [
  { id: 'all', label: '🌐 Todos los Géneros', icon: '🎛️' },
  { id: 'soul_jazz', label: '🎷 Soul Jazz', icon: '🎷' },
  { id: 'rare_soul', label: '💎 Rare Soul & Deep Funk', icon: '💎' },
  { id: 'jazz_rock', label: '🎸 Jazz Rock & Prog', icon: '🎸' },
  { id: 'ambient', label: '🌌 Ambiental & Library', icon: '🌌' },
  { id: 'japanese', label: '🇯🇵 Japanese Fusion & City Pop', icon: '🇯🇵' },
  { id: 'breaks', label: '🥁 Drum Breaks', icon: '🥁' },
];

export const CURATED_YOUTUBE_SAMPLES = [
  // ── 🎷 SOUL JAZZ ──────────────────────────────────────────────────────────
  {
    id: 'kgQGkq04xLA',
    title: "Vernon Garrett - Just Ain't My Day",
    artist: 'Vernon Garrett',
    genre: 'soul_jazz',
    genreLabel: 'Soul Jazz / Blues',
    vibe: 'Vientos oscuros, tempo lento y textura analógica cruda',
  },
  {
    id: '40JmEj0_aVM',
    title: 'Bob James - Angela (Theme from Taxi)',
    artist: 'Bob James',
    genre: 'soul_jazz',
    genreLabel: 'Soul Jazz / Fusion',
    vibe: 'Fender Rhodes melancólico y bajo redondo (oro puro para hip hop)',
  },
  {
    id: 'kgl_s3t7Y60',
    title: 'Roy Ayers - Everybody Loves the Sunshine',
    artist: 'Roy Ayers Ubiquity',
    genre: 'soul_jazz',
    genreLabel: 'Soul Jazz / Groove',
    vibe: 'Vibráfono etéreo, sintetizador ARP y coros de verano',
  },
  {
    id: 'O4_ghhh1jQo',
    title: 'Donald Byrd - Places and Spaces',
    artist: 'Donald Byrd (prod. Mizell Bros)',
    genre: 'soul_jazz',
    genreLabel: 'Soul Jazz / Funk',
    vibe: 'Cuerdas exuberantes, trompeta aérea y bajo eléctrico galopante',
  },
  {
    id: 'qRknp_fL_dE',
    title: 'Lonnie Liston Smith - Expansions',
    artist: 'Lonnie Liston Smith',
    genre: 'soul_jazz',
    genreLabel: 'Cosmic Soul Jazz',
    vibe: 'Clásico espiritual con piano eléctrico y percusión afro-cubana',
  },
  {
    id: 'ZcqZfXUj3fI',
    title: 'Dorothy Ashby - The Moving Finger',
    artist: 'Dorothy Ashby',
    genre: 'soul_jazz',
    genreLabel: 'Harp Soul Jazz',
    vibe: 'Arpa celestial y groove de batería sampleado por J Dilla y Pete Rock',
  },
  {
    id: 'JkK8g6FMEXE',
    title: "George Benson - Breezin'",
    artist: 'George Benson',
    genre: 'soul_jazz',
    genreLabel: 'Smooth Soul Jazz',
    vibe: 'Guitarra Ibanez aterciopelada y cuerdas suaves',
  },
  {
    id: 'VnZlAystWJw',
    title: 'Grover Washington Jr. - Just the Two of Us',
    artist: 'Grover Washington Jr. & Bill Withers',
    genre: 'soul_jazz',
    genreLabel: 'Soul Jazz',
    vibe: 'Acordes inconfundibles de piano eléctrico y saxofón sedoso',
  },
  {
    id: 'S1CilOzfYB0',
    title: 'Horace Silver - Song For My Father',
    artist: 'Horace Silver',
    genre: 'soul_jazz',
    genreLabel: 'Hard Bop / Soul Jazz',
    vibe: 'El riff de bajo y piano más famoso de Blue Note Records',
  },
  {
    id: '6c07mR8EPr8',
    title: 'Ahmad Jamal - I Love Music',
    artist: 'Ahmad Jamal Trio',
    genre: 'soul_jazz',
    genreLabel: 'Cool Jazz / Soul Jazz',
    vibe: 'Acordes de piano suspendidos (sample maestro de "The World Is Yours" de Nas)',
  },

  // ── 💎 RARE SOUL & DEEP FUNK ──────────────────────────────────────────────
  {
    id: 'JqOqUbK6g_s',
    title: 'Sylvia Striplin - Give Me Your Love',
    artist: 'Sylvia Striplin',
    genre: 'rare_soul',
    genreLabel: 'Rare Soul / Boogie',
    vibe: 'Voz femenina brillante y bajo disco-funk (sampleado por Biggie)',
  },
  {
    id: 'VbxgYlcNxE8',
    title: 'Shuggie Otis - Strawberry Letter 23',
    artist: 'Shuggie Otis',
    genre: 'rare_soul',
    genreLabel: 'Psychedelic Soul',
    vibe: 'Guitarras con phaser, timbres de glockenspiel y soul lo-fi de culto',
  },
  {
    id: 'h7GZLRxVUU4',
    title: 'Labi Siffre - I Got The...',
    artist: 'Labi Siffre',
    genre: 'rare_soul',
    genreLabel: 'Deep Funk & Soul',
    vibe: 'La segunda mitad es el break más contagioso de la historia (Eminem)',
  },
  {
    id: 'K1b8AhIsSYQ',
    title: 'Bill Withers - Lovely Day',
    artist: 'Bill Withers',
    genre: 'rare_soul',
    genreLabel: 'Classic Soul',
    vibe: 'Bajo envolvente, guitarra rítmica limpia y voz cálida',
  },
  {
    id: 'z6r0jD2L3gM',
    title: "Darondo - Didn't I",
    artist: 'Darondo',
    genre: 'rare_soul',
    genreLabel: 'Deep Bay Soul',
    vibe: 'Falsete desgarrador, cuerdas flotantes y guitarra soul desnuda',
  },
  {
    id: 'fX6t7L0Xo0c',
    title: "Syl Johnson - Is It Because I'm Black",
    artist: 'Syl Johnson',
    genre: 'rare_soul',
    genreLabel: 'Conscious Deep Soul',
    vibe: 'Reverb analógica profunda y metales desgarradores de Chicago',
  },
  {
    id: '9P2dYfJk9-0',
    title: 'Wendy Rene - After Laughter Comes Tears',
    artist: 'Wendy Rene (Stax 1964)',
    genre: 'rare_soul',
    genreLabel: 'Stax Rare Soul',
    vibe: 'Órgano de iglesia lúgubre y voz quebrada (base de Wu-Tang Clan)',
  },
  {
    id: 'zGDz4b9s1uE',
    title: 'Baby Huey - Hard Times',
    artist: 'Baby Huey & The Babysitters',
    genre: 'rare_soul',
    genreLabel: 'Heavy Soul & Funk',
    vibe: 'Groove de bajo aplastante, viento seco y líricas crudas',
  },
  {
    id: 'v_FqP91iU2Y',
    title: "Ann Peebles - I Can't Stand the Rain",
    artist: 'Ann Peebles',
    genre: 'rare_soul',
    genreLabel: 'Hi Records Soul',
    vibe: 'Caja de ritmos analógica tímida, cuerdas dramáticas y caja seca',
  },
  {
    id: 't8f_Qn9Xp8Y',
    title: "24-Carat Black - Ghetto: Misfortune's Wealth",
    artist: 'The 24-Carat Black',
    genre: 'rare_soul',
    genreLabel: 'Orchestral Deep Soul',
    vibe: 'Sinfonía oscura de soul conceptual (favorito absoluto de Madlib y Dilla)',
  },

  // ── 🎸 JAZZ ROCK & PROGRESSIVE ROCK ───────────────────────────────────────
  {
    id: 'T0ZGNFBpF60',
    title: 'Cortex - Troupeau Bleu',
    artist: 'Cortex',
    genre: 'jazz_rock',
    genreLabel: 'French Jazz Rock / Prog',
    vibe: 'Fender Rhodes cósmico, bajo funky y scat vocal (MF DOOM, Tyler The Creator)',
  },
  {
    id: '4fG7L6k9v3w',
    title: 'Soft Machine - Penny Hitch',
    artist: 'Soft Machine',
    genre: 'jazz_rock',
    genreLabel: 'Canterbury Progressive / Jazz',
    vibe: 'Bajo fuzz envolvente, piano eléctrico y texturas psicodélicas complejas',
  },
  {
    id: 'h1g5c6k9p8Z',
    title: 'Mahavishnu Orchestra - You Know You Know',
    artist: 'Mahavishnu Orchestra',
    genre: 'jazz_rock',
    genreLabel: 'Jazz Rock Fusion',
    vibe: 'Línea de bajo hipnótica y batería de Billy Cobham (Massive Attack, Mos Def)',
  },
  {
    id: 'pqashW66D7o',
    title: 'Weather Report - Birdland',
    artist: 'Weather Report (Jaco Pastorius)',
    genre: 'jazz_rock',
    genreLabel: 'Jazz Rock / Fusion',
    vibe: 'Bajo fretless brillante y sintetizadores polifónicos con melodías ricas',
  },
  {
    id: 'RhNdXXVYx9U',
    title: 'Camel - Lady Fantasy',
    artist: 'Camel',
    genre: 'jazz_rock',
    genreLabel: 'Symphonic Progressive Rock',
    vibe: 'Guitarras con delay flotante y teclados de ensueño de 1975',
  },
  {
    id: 'J3G4L2p9v7w',
    title: 'Placebo - Humpty Dumpty',
    artist: 'Placebo (Marc Moulin)',
    genre: 'jazz_rock',
    genreLabel: 'European Jazz Rock / Rare Groove',
    vibe: 'Groove de batería pesado con solo de sintetizador Moog analógico',
  },

  // ── 🌌 MÚSICA AMBIENTAL & LIBRARY MUSIC ──────────────────────────────────
  {
    id: 'aKw5mbz53N8',
    title: 'Brian Eno - An Ending (Ascent)',
    artist: 'Brian Eno',
    genre: 'ambient',
    genreLabel: 'Ambient Masterpiece',
    vibe: 'Sintetizadores Yamaha CS-80 flotando en reverb celestial y atemporal',
  },
  {
    id: 'IUVmcZTLfZ8',
    title: 'Mort Garson - Plantasia',
    artist: 'Mort Garson (1976)',
    genre: 'ambient',
    genreLabel: 'Vintage Moog Ambient',
    vibe: 'Arpegios de sintetizador modular cálidos, inocentes y súper sampleables',
  },
  {
    id: 'T7m9L2v4X8s',
    title: 'Hiroshi Yoshimura - Green',
    artist: 'Hiroshi Yoshimura',
    genre: 'ambient',
    genreLabel: 'Japanese Kankyo Ongaku',
    vibe: 'Sintetizador FM sutil, gotas de lluvia y texturas espaciales relajantes',
  },
  {
    id: 'p4L9v7M2K3s',
    title: 'Janko Nilovic - In the Space',
    artist: 'Janko Nilovic',
    genre: 'ambient',
    genreLabel: 'Library Music / Space Funk',
    vibe: 'Cuerdas cinemáticas dramáticas y bombo seco (sample de "D.O.A." de Jay-Z)',
  },
  {
    id: 'v7P5m4L2w9s',
    title: 'Piero Umiliani - Crepuscolo sul Mare',
    artist: 'Piero Umiliani',
    genre: 'ambient',
    genreLabel: 'Italian Library / Soundtrack',
    vibe: 'Guitarra acústica de 12 cuerdas, marimba y brisa marina nostálgica',
  },
  {
    id: 'k8P5m4L2w9s',
    title: 'Keith Mansfield - Funky Fanfare',
    artist: 'Keith Mansfield (KPM Library)',
    genre: 'ambient',
    genreLabel: 'KPM Library Funk',
    vibe: 'Vientos majestuosos de televisión retro de los 70 y caja contundente',
  },

  // ── 🇯🇵 JAPANESE JAZZ FUSION & CITY POP ───────────────────────────────────
  {
    id: 'G-kK6q2i9-0',
    title: 'Casiopea - Midnight Rendezvous',
    artist: 'Casiopea',
    genre: 'japanese',
    genreLabel: 'Japanese Jazz Fusion',
    vibe: 'Bajo slap ultra veloz, sintetizadores brillantes y batería hiper técnica',
  },
  {
    id: 's7P5m4L2w9s',
    title: 'Tatsuro Yamashita - Sparkle',
    artist: 'Tatsuro Yamashita',
    genre: 'japanese',
    genreLabel: 'City Pop / Funk',
    vibe: 'El riff de guitarra funk rítmica más perfecto de Tokio de 1982',
  },
  {
    id: 'm7P5m4L2w9s',
    title: 'Minako Yoshida - Midnight Driver',
    artist: 'Minako Yoshida',
    genre: 'japanese',
    genreLabel: 'City Pop / Boogie Funk',
    vibe: 'Línea de bajo sintetizado agresivo y coros nocturnos de neón',
  },
  {
    id: '7jP8m4L2w9s',
    title: 'Masayoshi Takanaka - Blue Lagoon',
    artist: 'Masayoshi Takanaka',
    genre: 'japanese',
    genreLabel: 'Resort Jazz Rock Fusion',
    vibe: 'Guitarra eléctrica veraniega con compás latino-funk inolvidable',
  },

  // ── 🥁 DRUM BREAKS ───────────────────────────────────────────────────────
  {
    id: 'rV6rNscn48o',
    title: 'The Honey Drippers - Impeach The President',
    artist: 'The Honey Drippers',
    genre: 'breaks',
    genreLabel: 'Essential Drum Break',
    vibe: 'El ritmo fundamental del Hip Hop de los 90 (Notorious B.I.G., Nas, 2Pac)',
  },
  {
    id: '1u4XkZ11N78',
    title: "Skull Snaps - It's a New Day",
    artist: 'Skull Snaps',
    genre: 'breaks',
    genreLabel: 'Legendary Breakbeat',
    vibe: 'Golpe de caja crujiente y charles sutil e ideal para picar en 16 cortes',
  },
  {
    id: 'F2zJq4q2M9c',
    title: "The Soul Searchers - Ashley's Roachclip",
    artist: 'The Soul Searchers',
    genre: 'breaks',
    genreLabel: 'Unwind Yourself Break',
    vibe: 'Caja limpia, congas y guitarra wah-wah (Eric B. & Rakim, Run-DMC)',
  },
];

/**
 * Sugerencias de búsqueda profunda para Crate Digging en YouTube
 */
export const SAMPLE_SEARCH_SUGGESTIONS = [
  'rare soul 1970s 45rpm vinyl',
  'soul jazz rhodes fender blue note',
  'rare jazz rock progressive fusion',
  'japanese ambient kankyo ongaku vinyl',
  'italian library music 1970 funk',
  'kpm library music drum break',
  'french jazz funk cortex rhodes',
  'deep funk drum break 1971',
  'japanese city pop boogie 1982',
  'spiritual cosmic jazz harp lonnie liston',
];
